### ISSUE TITLE
ImportError: cannot import name UserList

### ISSUE THREAD

**Issue by meng89** [meng89/ipodshuffle#1]
root@debian:~# teresa help
Traceback (most recent call last):
  File "/usr/local/bin/teresa", line 9, in <module>
    load_entry_point('ipodshuffle==0.2.4', 'console_scripts', 'teresa')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2386, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ipodshuffle/**init**.py", line 1, in <module>
    from .shuffle import Shuffle, Playlist, Track, PL_MAP
  File "/usr/local/lib/python2.7/dist-packages/ipodshuffle/shuffle.py", line 11, in <module>
    from collections import UserList as List
ImportError: cannot import name UserList

**Comment by meng89** [comment]
`root@debian:~# cat /usr/local/bin/teresa
#!/usr/bin/python

# EASY-INSTALL-ENTRY-SCRIPT: 'ipodshuffle==0.2.4','console_scripts','teresa'

**requires** = 'ipodshuffle==0.2.4'
import sys
from pkg_resources import load_entry_point

if **name** == '**main**':
    sys.exit(
        load_entry_point('ipodshuffle==0.2.4', 'console_scripts', 'teresa')()
    )
`

**Comment by meng89** [comment]
Use pip3 install ipodshuffle to fix this，I changed README.org
